/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonArticleItem: typeof import('./src/components/CommonArticleItem/index.vue')['default']
    CommonBg: typeof import('./src/components/CommonBg/index.vue')['default']
    CommonCard: typeof import('./src/components/CommonCard/index.vue')['default']
    CommonCategoryItem: typeof import('./src/components/CommonCategoryItem/index.vue')['default']
    CommonCol: typeof import('./src/components/CommonCol/index.vue')['default']
    CommonDialog: typeof import('./src/components/CommonDialog/index.vue')['default']
    CommonFooter: typeof import('./src/components/CommonFooter/index.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader/index.vue')['default']
    CommonHeaderRight: typeof import('./src/components/CommonHeaderRight/index.vue')['default']
    CommonIcon: typeof import('./src/components/CommonIcon/index.vue')['default']
    CommonLoading: typeof import('./src/components/CommonLoading/index.vue')['default']
    CommonLogo: typeof import('./src/components/CommonLogo/index.vue')['default']
    CommonNav: typeof import('./src/components/CommonNav/index.vue')['default']
    CommonPagination: typeof import('./src/components/CommonPagination/index.vue')['default']
    CommonSvg: typeof import('./src/components/CommonSvg/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
